spring:
  application:
    name: exam
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  datasource:
    url: jdbc:mysql://localhost:3306/exam_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "056519"
    driver-class-name: com.mysql.cj.jdbc.Driver

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zzu.exam
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# jwt配置
exam:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: examggggggggggggggggggggggggggggggggg
    # 设置jwt过期时间：一个月
    user-ttl: 2592000000
    # 设置前端传递过来的令牌名称
    user-token-name: token

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zzu.exam.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
